//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAndControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointAndControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a Device failed. Wrong number of parameters.
        /// </summary>
        internal static string AddDeviceError {
            get {
                return ResourceManager.GetString("AddDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} Positions added.
        /// </summary>
        internal static string AddDevVec {
            get {
                return ResourceManager.GetString("AddDevVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} got an additional position.
        /// </summary>
        internal static string AdditionalDevCoords {
            get {
                return ResourceManager.GetString("AdditionalDevCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation error, please try again.
        /// </summary>
        internal static string CalculationError {
            get {
                return ResourceManager.GetString("CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command arrived! devID: {0}; cmdID: {1}; value: {2}, wlanAdr:{3}.
        /// </summary>
        internal static string CmdArrivedLog {
            get {
                return ResourceManager.GetString("CmdArrivedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates added.
        /// </summary>
        internal static string CoordinatesAdded {
            get {
                return ResourceManager.GetString("CoordinatesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is now located to another position.
        /// </summary>
        internal static string DevCoordsReplaced {
            get {
                return ResourceManager.GetString("DevCoordsReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device deleted.
        /// </summary>
        internal static string DevDeleted {
            get {
                return ResourceManager.GetString("DevDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Not Found. Deletion failed.
        /// </summary>
        internal static string DevNotFoundDeletion {
            get {
                return ResourceManager.GetString("DevNotFoundDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of gesturecontrol failed.
        /// </summary>
        internal static string GesturecontrolError {
            get {
                return ResourceManager.GetString("GesturecontrolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t establish HTTP connection.
        /// </summary>
        internal static string HTTPConnEstablishFailure {
            get {
                return ResourceManager.GetString("HTTPConnEstablishFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP connection error. 
        ///Command could not be executed.
        /// </summary>
        internal static string HTTPConnFailure {
            get {
                return ResourceManager.GetString("HTTPConnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IP and Port given for communication. Device not created.
        /// </summary>
        internal static string IPPortMissing {
            get {
                return ResourceManager.GetString("IPPortMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect placement changed.
        /// </summary>
        internal static string KinectPlacementChanged {
            get {
                return ResourceManager.GetString("KinectPlacementChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More vectors needed for calculation.
        /// </summary>
        internal static string MoreVectorsRequired {
            get {
                return ResourceManager.GetString("MoreVectorsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Coordinates added.
        /// </summary>
        internal static string NoCoordAdded {
            get {
                return ResourceManager.GetString("NoCoordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device found.
        /// </summary>
        internal static string NoDevFound {
            get {
                return ResourceManager.GetString("NoDevFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User with gesture identified.
        /// </summary>
        internal static string NoGestureFound {
            get {
                return ResourceManager.GetString("NoGestureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kinect connected to the System.
        /// </summary>
        internal static string NoKinAvailable {
            get {
                return ResourceManager.GetString("NoKinAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Person found by Kinect.
        /// </summary>
        internal static string NoPersonFoundKin {
            get {
                return ResourceManager.GetString("NoPersonFoundKin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius is missing or has wromg Format.
        /// </summary>
        internal static string NoRadiusWrongFormat {
            get {
                return ResourceManager.GetString("NoRadiusWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Person in the view of the kinect camera.
        /// </summary>
        internal static string NoUserInImage {
            get {
                return ResourceManager.GetString("NoUserInImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For that command values are needed, but not transmitted.
        /// </summary>
        internal static string NoValues {
            get {
                return ResourceManager.GetString("NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugwise-Path changed.
        /// </summary>
        internal static string PWCompChange {
            get {
                return ResourceManager.GetString("PWCompChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register yourself at the system first.
        /// </summary>
        internal static string RegistrationRequest {
            get {
                return ResourceManager.GetString("RegistrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string ResponseLog {
            get {
                return ResourceManager.GetString("ResponseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left the Room.
        /// </summary>
        internal static string RoomLeft {
            get {
                return ResourceManager.GetString("RoomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures of the room were changed.
        /// </summary>
        internal static string RoommeasuresChanged {
            get {
                return ResourceManager.GetString("RoommeasuresChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A device with the given or created Device ID does already exist.
        /// </summary>
        internal static string SameDevIDEx {
            get {
                return ResourceManager.GetString("SameDevIDEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server will be shut down.
        /// </summary>
        internal static string ServerShutDown {
            get {
                return ResourceManager.GetString("ServerShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified device not found.
        /// </summary>
        internal static string SpecifiedDeviceNotFound {
            get {
                return ResourceManager.GetString("SpecifiedDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting HTTP Server on {0} : {1}.
        /// </summary>
        internal static string StartingHTTPServer {
            get {
                return ResourceManager.GetString("StartingHTTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TCPConnEstablishFailure {
            get {
                return ResourceManager.GetString("TCPConnEstablishFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP connection error. \n Command could not be executed.
        /// </summary>
        internal static string TCPConnFailure {
            get {
                return ResourceManager.GetString("TCPConnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a command!.
        /// </summary>
        internal static string TypeConsoleCommand {
            get {
                return ResourceManager.GetString("TypeConsoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device unknown.
        /// </summary>
        internal static string UnknownDev {
            get {
                return ResourceManager.GetString("UnknownDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Wlan-Adress {0} was added.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Wlan-Adress {0} already exists.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed Parameter for the request not found: {0}.
        /// </summary>
        internal static string WrongParameter {
            get {
                return ResourceManager.GetString("WrongParameter", resourceCulture);
            }
        }
    }
}
